apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sebmrgn/gitops-dir-structure.git
    targetRevision: HEAD
    path: apps/helm/charts/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook