apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/sebmrgn/gitops-dir-structure.git
    targetRevision: HEAD
    path: apps/helm/charts/podinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
#  helm:
#    parameters:
#      - name: ui.colour
#        value: "#34577c"
  syncPolicy:
    automated:
      prune: true
